#!/bin/bash

A=$1
B=$2

if [[ -n "$A" ]]
then
  echo "O primeiro valor é válido: $A"
else
  echo "O primeiro valor é nulo"
  exit 1
fi

if [[ -n "$B" ]]
then
  echo "O segundo valor é válido: $B"
else
  echo "O segundo valor é nulo"
  exit 1
fi

if [[ "$A" -eq "$B" ]]
then
  echo "A e B são iguais"
fi

if [[ "$A" -ne "$B" ]]
then
  echo "A e B são diferentes"
fi

if [[ "$A" -gt "$B" ]]
then
  echo "A é maior que B"
fi

if [[ "$A" -lt "$B" ]]
then
  echo "A é menor que B"
fi

exit 0
