#!/bin/bash

echo "Nome do script: $0"

echo "Parametro 1: $1"

echo "Parametro 2: $2"

echo "Parametro 3: $3"

echo "Parametro 4: $4"

echo "Parametro 5: $5"

echo "Parametro 6: $6"

echo "Parametro 7: $7"

echo "Parametro 8: $8"

echo "Parametro 9: $9"

echo "Parametro 10: $10"

echo "Parametro 11: $11"
